version: '3.8'
services:
  db:
    image: postgres:15
    container_name: dsp_postgres
    environment:
      POSTGRES_USER: dsp_user
      POSTGRES_PASSWORD: dsp_password
      POSTGRES_DB: dsp_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dsp_network

volumes:
  pg_data:

networks:
  dsp_network:
    driver: bridge